sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - '8'
before_script:
  - npm prune
script:
  - npm run lint
  - npm run test:cover
  - npm run build
after_success:
  - npm run coveralls
  - npx travis-deploy-once "npx semantic-release"

